# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            8.0,  # Minimum supported by Minecraft
            11,   # Current Java LTS
            16    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 1 - Checkout repository
        uses: actions/checkout@v2
      - name: 2 - Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 3 - Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: 4 - Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: 5 - Build
        run: ./gradlew build
      - name: 6 - Capture & upload build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
