name: Build Chocobacon
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8.0, 16 ]
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 1 - Checkout repository
        uses: actions/checkout@v2
      - name: 2 - Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 3 - Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: 4 - Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: 5 - Build
        run: ./gradlew build
      - name: 6 - Capture & upload build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
